sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y --no-install-recommends texlive-full
  - sudo apt-get install -y latexmk

script:
  latexmk -pdf -interaction=nonstopmode -outdir=build -auxdir=build whitepaper.tex
